Добавляет первую версию ридми
doka-guide/.github pull request #4
Opened 2021-09-29 15:29 UTC by tachisis

2021-09-29 15:29 UTC, tachisis commented on README.md
> +Дока состоит из двух репозиториев: [платформа](https://github.com/doka-guide/platform) на базе [Eleventy](https://www.11ty.dev) собирает статьи из репозитория с контентом (мы сейчас в нём), и на выхо
```suggestion
Дока состоит из двух репозиториев: [платформа](https://github.com/doka-guide/platform) на базе [Eleventy](https://www.11ty.dev) собирает статьи из репозитория с контентом, и на выходе получается наш красивый [сайт](https://doka.guide/).
```

2021-09-29 15:34 UTC, tachisis commented on README.md
> +# Дока
```suggestion
# U・ᴥ・U
```

2021-09-29 15:34 UTC, tachisis commented on README.md
> +[О проекте](https://github.com/doka-guide/content/blob/main/pages/about/index.md)
```suggestion
💫 [О проекте](https://github.com/doka-guide/content/blob/main/pages/about/index.md)
```

2021-09-29 15:34 UTC, tachisis commented on README.md
> +[Контрибьютинг](https://github.com/doka-guide/content/blob/main/docs/contributing.md)
```suggestion
🚀 [Контрибьютинг](https://github.com/doka-guide/content/blob/main/docs/contributing.md)
```

2021-09-29 15:34 UTC, tachisis commented on README.md
> +[Документация](https://github.com/doka-guide/content/tree/main/docs)
```suggestion
📄 [Документация](https://github.com/doka-guide/content/tree/main/docs)
```

2021-09-29 15:34 UTC, tachisis commented on README.md
> +Дока — это добрый [справочник для веб-разработчиков](https://doka.guide). В нём аккумулируются знания сообщества: от формального синтаксиса и списка возможностей до реальных случаев применения.
```suggestion
**Дока** — это добрый [справочник для веб-разработчиков](https://doka.guide). В нём аккумулируются знания сообщества: от формального синтаксиса и списка возможностей до реальных случаев применения.
```

2021-09-29 16:04 UTC, pepelsbey requested changes

2021-09-29 16:04 UTC, pepelsbey commented on README.md
> +Дока состоит из двух репозиториев: [платформа](https://github.com/doka-guide/platform) на базе [Eleventy](https://www.11ty.dev) собирает статьи из репозитория с [контентом](https://github.com/doka-gu
```suggestion
Дока состоит из двух репозиториев: [платформа](https://github.com/doka-guide/platform) собирает статьи из репозитория с [контентом](https://github.com/doka-guide/content/), и на выходе получается наш красивый [сайт](https://doka.guide/).
```

Думаю здесь можно ещё более кратко

2021-09-29 23:02 UTC, igsekor approved these changes

2021-09-30 08:38 UTC, furtivite commented on README.md
> +Дока состоит из двух репозиториев: [платформа](https://github.com/doka-guide/platform) на базе [Eleventy](https://www.11ty.dev) собирает статьи из репозитория с [контентом](https://github.com/doka-gu
Да, мне кажется, что тут мы просто покажем, почему репозиториев два, а там дальше те, кто заинтересуется платформой, зайдут и там посмотрят на чём она работает.

2021-09-30 15:00 UTC, tachisis commented on README.md
> +Дока состоит из двух репозиториев: [платформа](https://github.com/doka-guide/platform) на базе [Eleventy](https://www.11ty.dev) собирает статьи из репозитория с [контентом](https://github.com/doka-gu
@pepelsbey я сделала еще радикальнее и компактнее

2021-09-30 15:33 UTC, pepelsbey approved these changes

2021-09-30 17:36 UTC, furtivite approved these changes

2021-09-30 17:36 UTC, merged